kafka.bootstrap.servers=127.0.0.1:9092
kafka.topic.raw=behavior_raw
kafka.topic.late=behavior_late
kafka.group.id=bigdata-etl-realtime
flink.parallelism=4
watermark.max-out-of-orderness.seconds=10
watermark.idle-timeout.seconds=10
checkpoint.interval-ms=60000
doris.user=root
doris.password=
doris.detail.load-url=http://127.0.0.1:8030/api/bigdata_analytics/dwd_event_detail/_stream_load
doris.aggregate.load-url=http://127.0.0.1:8030/api/bigdata_analytics/dws_event_1m/_stream_load
doris.detail.batch-size=5000
doris.detail.flush-ms=3000
doris.aggregate.batch-size=1000
doris.aggregate.flush-ms=2000
